apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: /upgrade/acm/ocp-release-images/ocp4.14.23/
mirror:
  platform:
    channels:
      - name: stable-4.14
        minVersion: 4.14.23
        maxVersion: 4.14.23
